### ISSUE TITLE
v11 Workflow Launcher Block Error

### ISSUE THREAD

**Issue by kcsnow** [secc/RockPlugins#89]
When using the Workflow Launcher block after upgrading to Rock RMS v11, I receive this error:

Error Loading Block: Workflow Launcher Show Details
C:\inetpub\wwwroot\Plugins\org_secc\Workflow\WorkflowLauncher.ascx(34): error CS0619: 'DataViewPicker' is obsolete: 'Use DataViewItemPicker instead'

`at System.Web.Compilation.BuildManager.PostProcessFoundBuildResult(BuildResult result, Boolean keyFromVPP, VirtualPath virtualPath)

   at System.Web.Compilation.BuildManager.GetBuildResultFromCacheInternal(String cacheKey, Boolean keyFromVPP, VirtualPath virtualPath, Int64 hashCode, Boolean ensureIsUpToDate)

   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)

   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)

   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)

   at System.Web.Compilation.BuildManager.GetVPathBuildResult(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean ensureIsUpToDate)

   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at Rock.Web.UI.RockPage.OnInit(EventArgs e)`

**Comment by cbump** [comment]
Hi @kcsnow thanks for reporting this.  It should be fixed in the latest version of the plugin that is now available in the Rock shop.  Thank you!
